# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moim' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Add Extention
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  # Pods for moim

  target 'moimTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'moimUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
